=== ramkumar-kr/wp-lab-exam-preparation/five.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="stu_data">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="student">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="usn" type="xs:string"></xs:element>
                        <xs:element name="name" type="xs:string"></xs:element>
                        <xs:element name="email" type="xs:string"></xs:element>
                        <xs:element name="phone" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ramkumar-kr/wp-lab-exam-preparation/five.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="five.css"?>

<stu_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="five.xsd">
    <student>
        <usn>1RV11IS042</usn>
        <name>Ram Kumar K R</name>
        <email>ramkumarkr@rvce.edu.in</email>
        <phone>5858585858</phone>
    </student>
    <student>
        <usn>1RV11IS021</usn>
        <name>Ganesh Arkalgud</name>
        <email>ganesh.arkalgud@rvce.edu.in</email>
        <phone>9898989898</phone>
    </student>
    <student>
        <usn>1RV11IS040</usn>
        <name>Rahul R</name>
        <email>sirrahul@rvce.edu.in</email>
        <phone>8787878787</phone>
    </student>
    <student>
        <usn>1RV11IS056</usn>
        <name>Ujjwal Gulecha</name>
        <email>ujjwalgulecha@rvce.edu.in</email>
        <phone>6565656565</phone>
    </student>
</stu_data>
